kind: Service
apiVersion: v1
metadata:
  name: mangle-service
  labels:
    app: mangle
    environment: test
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: mangle
    environment: test
  ports:
  - name: mangle-https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: mangle-cluster-port
    port: 5701
    protocol: TCP
    targetPort: 5701

