#Its placeholder for codecov to fail build below certain coverage percentage, currently the rule is not working with mangle github repo.
coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        # basic
        target: 90%
        threshold: 90%
        base: auto