{{ if .Values.image.useSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.secretName }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.image.externalRegistry (printf "%s:%s" .Values.image.user .Values.image.pass | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson
{{ end }}